fieldLayouts:
  f4e014f7-5702-4894-9e80-6f6f481907bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Drink Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 29764101-4023-4a30-aef2-d08024b0233e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90c6a0b6-edb9-43e1-8ddc-c4172b0b9724
        userCondition: null
handle: alcoholDrinks
hasTitleField: true
name: 'alcohol drinks'
section: 4e90476a-1613-447e-9942-30d691eec5b1 # drinks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
