fieldLayouts:
  f4e014f7-5702-4894-9e80-6f6f481907bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Drink Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 29764101-4023-4a30-aef2-d08024b0233e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2fdf6f3c-8796-4125-a22a-392fe3486fef # introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4259f1f9-ad16-4df3-9eb7-7669a9a60f4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5b7d0fb-075f-4551-ab53-c7a37d7ea905 # Information Drinks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c86c31f-cbc0-47c3-ab49-94ba6c6f73cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51b05e04-81a8-4074-bb1c-64f3090a35c6 # Alcohol percentage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 811eb3ef-270e-4950-8827-97e09c3a07a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f0f0a2ff-68fd-4217-93b1-7318025da83b # Price drinks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79fb3185-4d19-4811-809a-22f430fe1b40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 90c6a0b6-edb9-43e1-8ddc-c4172b0b9724
        userCondition: null
handle: alcoholDrinks
hasTitleField: true
name: 'alcohol drinks'
section: 4e90476a-1613-447e-9942-30d691eec5b1 # drinks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
