columnSuffix: zfzzucta
contentColumnType: 'decimal(12,2)'
fieldGroup: 892e899e-bc4d-426a-abb8-850855a6fc7c # Drinks
handle: priceDrinks
instructions: 'The price of the drinks (number only)'
name: 'Price drinks'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: €
  previewCurrency: EUR
  previewFormat: currency
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
