dateModified: 1704992297
email:
  fromEmail: r0906880@student.thomasmore.be
  fromName: 'Drank Webshop'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  aboutUs:
    hasUrls: true
    name: 'about Us'
    settings:
      path: '@webroot/images/About'
    type: craft\fs\Local
    url: '@web/images/About'
  drinks:
    hasUrls: true
    name: drinks
    settings:
      path: '@webroot/images/dranken'
    type: craft\fs\Local
    url: '@web/images/dranken'
  home:
    hasUrls: true
    name: home
    settings:
      path: '@webroot/images/Frontpage'
    type: craft\fs\Local
    url: '@web/images/Frontpage'
meta:
  __names__:
    2fdf6f3c-8796-4125-a22a-392fe3486fef: introduction # introduction
    3d9e1db9-d8e4-4a7c-9a47-ca0b0dac0261: Common # Common
    3d1094d4-9576-466e-8f54-d264d7286642: 'Info about' # Info about
    4e90476a-1613-447e-9942-30d691eec5b1: drinks # drinks
    6b5f5717-efc9-40c6-9d68-97b86792a46c: Default # Default
    06fe3a33-66ad-4be8-9254-a3271ae424ed: 'about Us' # about Us
    8edf0eb0-db84-407e-8941-f20dada533ee: 'store categories' # store categories
    9c58ac58-2bbb-49cf-8e49-c1f4f9364f6a: 'enkel alcohol' # enkel alcohol
    9c722366-6570-4938-b9ff-9f3d55620afe: 'store Categories' # store Categories
    18e745c4-9c85-4f4c-9219-09e2ba15599c: 'Store Categories' # Store Categories
    51b05e04-81a8-4074-bb1c-64f3090a35c6: 'Alcohol percentage' # Alcohol percentage
    224b5a40-80ce-447d-8be5-4e349e553bcd: header1 # header1
    312c1641-3732-473d-82d8-212a18bc8443: Default # Default
    387b84cf-e0f9-41a7-976d-9a2d94c8ee4d: 'Drank Webshop' # Drank Webshop
    597ef37d-ecf5-4ed9-92ef-7b0f956184dd: home # home
    892e899e-bc4d-426a-abb8-850855a6fc7c: Drinks # Drinks
    4228d972-2762-4d4c-b1a6-d69ac37ceefa: drinksVersion # drinksVersion
    a0cd8b19-e1b7-4968-86c8-25f1345172a0: drinks # drinks
    a092b4e1-f8a1-411a-8964-8779a4da42f7: home # home
    a3ea80b4-e1b2-40ba-9389-ad406905a942: 'Drank Webshop' # Drank Webshop
    a5b7d0fb-075f-4551-ab53-c7a37d7ea905: 'Information Drinks' # Information Drinks
    a16af4de-9170-42ba-9340-97ad4abfb3b2: home # home
    b957af1b-f8d8-43a7-9958-98856e4707c6: 'what we are all about' # what we are all about
    b4927f39-21eb-487f-9819-47b121ed4ca8: home # home
    bdfa53af-e91a-4d84-824e-a115eec9cd04: 'Page coppy' # Page coppy
    c0d44cc8-1c83-47d4-9b83-9ba94e0224dc: 'About us' # About us
    cbc6efb9-07dd-46a7-8965-d8c5bf50cd40: drinkImageSmall # drinkImageSmall
    e1d95b86-a3f8-45e9-b985-8605dde5b9d4: 'ons assortiment' # ons assortiment
    e5ae6272-fc40-4a83-ae00-6f7847500ae8: 'About us' # About us
    e9c3a8c7-917d-4e97-9b9b-c9113fac435a: test # test
    e671db06-f0c3-45b9-a032-192145ab9bc5: 'About us' # About us
    f0f0a2ff-68fd-4217-93b1-7318025da83b: 'Price drinks' # Price drinks
plugins:
  abm-tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      allow: 'Allow cookies'
      async_js: '1'
      auto_inject: ''
      decline: Decline
      defer_js: '1'
      disable_in_live_preview: ''
      dismiss: 'Got it!'
      dismiss_on_scroll: '1000'
      dismiss_on_timeout: '300'
      excluded_categories: null
      excluded_entry_types: null
      expiry_days: '1'
      honour_do_not_track_header: ''
      layout: block
      learn: 'Learn More'
      learn_more_link: 'http://cookiesandyou.com/'
      message: 'This website uses cookies to ensure you get the best experience on our website.'
      palette: default
      palette_banner: '000'
      palette_banner_text: ffffff
      palette_button: f1d600
      palette_button_text: '000000'
      palette_left_button_bg: f1d600
      palette_left_button_text: '000000'
      palette_link: ffffff
      position: bottom-left
      preload_css: ''
      revokable: ''
      secure_only: '1'
      target: _blank
      type: info
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  geoaddress:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      googleApiKey: AIzaSyDFY0QkI8ohMzEUWK373CvpOI9SRSmGFeo
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Drank Webshop'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
