defaultPlacement: end
enableVersioning: true
handle: home
name: home
propagationMethod: all
siteSettings:
  387b84cf-e0f9-41a7-976d-9a2d94c8ee4d: # Drank Webshop
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: home
type: single
